lines: 91
statements: 91
branches: 82
functions: 95
all: true
include:
  - 'src/**/*.*'
exclude:
  - 'src/**/*.test.*'
  - '**/__tests__/**/*'
report-dir: coverage
check-coverage: true
reporter:
  - 'html'
  - 'text-summary'
  - 'lcov'
