language: node_js
node_js:
  - 10
install:
  - yarn install

  - npm install codeclimate-test-reporter -g
script:
  - yarn build
  - yarn lint
  - yarn test
  - yarn coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  - yarn install
  - yarn semantic-release
