branches :
  only :
    - master
language : node_js
node_js :
  - 10
install :
  - yarn install

  - npm install codeclimate-test-reporter -g
script :
  - yarn lint
  - yarn test
  - yarn coverage
  - yarn build

after_script :
  - codeclimate-test-reporter < coverage/lcov.info
  - npm publish
