language: node_js
node_js:
  - 10
install:
  - yarn install

  - npm install codeclimate-test-reporter -g
script:
  - yarn build
  - yarn lint
  - yarn test
  - yarn coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn semantic-release
